name: Build Tailscale AAR

on:
  workflow_dispatch:

jobs:
  build-engine:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Go compiler
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up Java Environment
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK Environments
        uses: android-actions/setup-android@v3

      - name: Force Execute Android Native Compilation
        run: |
          chmod +x gradlew
          gradle :libtailscale:assembleRelease


