name: Build Tailscale AAR

on:
  workflow_dispatch:

jobs:
  build-engine:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Go compiler
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up Java Environment
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK & NDK
        uses: android-actions/setup-android@v3
        with:
          ndk-version: '23.1.7779620' # Installs the precise native tools needed for Go

      - name: Compile Go into Android Library (.aar)
        run: ./gradlew :libtailscale:assembleRelease

      - name: Save and Upload Completed Archive
        uses: actions/upload-artifact@v4
        with:
          name: libtailscale-release
          path: ./**/build/outputs/aar/*.aar

