name: Build Tailscale AAR

on:
  workflow_dispatch:

jobs:
  build-engine:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Go compiler
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Set up Java Environment
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK & NDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK Components
        run: |
          ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;23.1.7779620"

      - name: Install Go Mobile Bind Tools
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          gomobile init

      - name: Compile Library via Native Makefile
        run: |
          export ANDROID_NDK_HOME="${ANDROID_HOME}/ndk/23.1.7779620"
          make libtailscale

      - name: Save and Upload Completed Archive
        uses: actions/upload-artifact@v4
        with:
          name: libtailscale-release
          path: ./**/build/outputs/aar/*.aar


